// Raw FFI to libusb-1.0. Generated by bindgen at build time — see build.rs.
// This crate is intentionally unsafe and minimal. Safe wrappers live in `biospy-usb`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/libusb_bindings.rs"));
